### ISSUE TITLE
github action using 'TARGET_REPO_CDN' should be skipped if blank/missing (currently uses same repo)

### ISSUE THREAD

**Issue by duttonw** [qld-gov-au/qgds-vanilla#275]
```
 - name: Publish to qld-gov-au/qgds-vanilla-cdn
        uses: qld-gov-au/gha-cdn-version-tree-by-tag-builder@main
        with:
          repository: ${{ vars.TARGET_REPO_CDN }}
          git_ref: '${{ github.ref }}'
          branch: 'release'
          github_token: '${{ secrets.GH_TOKEN }}'
          github_pat: '${{ secrets.GH_PAT }}'
          source_folder: dist
        if: success()
```
